import './style/app.scss'
import './style/responsive.scss'
import './style/header.scss'
import type { Metadata } from 'next'
import React from 'react'
import Header from './header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout: React.FC<React.PropsWithChildren> = ({ children }) => {
  return (
    <html>
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=5, shrink-to-fit=no" />
        <title>Bryggverket</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
        <script async={true} src="https://identity.netlify.com/v1/netlify-identity-widget.js" />
        <link rel="apple-touch-icon" sizes="180x180" href="/image/favicon/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/image/favicon/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/image/favicon/favicon-16x16.png" />
        <link rel="manifest" href="/image/favicon/site.webmanifest" />
        <link rel="mask-icon" href="/image/favicon/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#000000" />
        <meta name="theme-color" content="#ffffff"></meta>
      </head>
      <body>
        <Header />
        <main className="content main">{children}</main>
      </body>
    </html>
  )
}
export default RootLayout
